name: CI / CD

on:
  push:
    branches:
      - main
jobs:
  build-deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Simulate test
        run: sh simulate_test.sh
