name: "Get Data"

on:
  schedule:
    - cron: "0 0 * * 0" # runs At 00:00 on Sunday.
  workflow_dispatch: # allows for manual invocation

jobs:
  get-data:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
      - run: poetry install
      - name: Run scripts
        run: echo "test"
